# Generated by Django 4.0.1 on 2022-01-29 19:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('main', '0005_remove_price_price_postfix_remove_price_price_prefix_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100, verbose_name='Full Name')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('phone_number', models.PositiveBigIntegerField(verbose_name='Phone number')),
                ('date', models.DateField(verbose_name='Date')),
                ('time_start', models.TimeField(verbose_name='Starts at')),
                ('time_finish', models.TimeField(verbose_name='Finishes at')),
                ('created_at', models.DateTimeField(auto_now=True, verbose_name='Created At')),
                ('is_confirmed', models.BooleanField(default=True, verbose_name='Confirm?')),
                ('is_paid', models.BooleanField(default=False, verbose_name='Paid?')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.service', verbose_name='Service')),
            ],
            options={
                'verbose_name': 'Booking',
                'verbose_name_plural': 'Bookings',
            },
        ),
    ]
