# Generated by Django 3.2.9 on 2021-12-08 16:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Body',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Body Type')),
                ('name_en', models.CharField(max_length=50, null=True, verbose_name='Body Type')),
                ('name_ru', models.CharField(max_length=50, null=True, verbose_name='Body Type')),
                ('name_fi', models.CharField(max_length=50, null=True, verbose_name='Body Type')),
                ('slug', models.SlugField(null=True, unique=True, verbose_name='URL Postfix')),
            ],
            options={
                'verbose_name': 'Body Type',
                'verbose_name_plural': 'Body Types',
            },
        ),
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=100, verbose_name='Brand')),
                ('model', models.CharField(max_length=100, verbose_name='Model')),
                ('year', models.PositiveIntegerField(verbose_name='Year')),
                ('vin', models.CharField(max_length=50, verbose_name='VIN-number')),
                ('color', models.CharField(max_length=50, verbose_name='Color')),
                ('color_en', models.CharField(max_length=50, null=True, verbose_name='Color')),
                ('color_ru', models.CharField(max_length=50, null=True, verbose_name='Color')),
                ('color_fi', models.CharField(max_length=50, null=True, verbose_name='Color')),
                ('description', models.TextField(verbose_name='Description')),
                ('description_en', models.TextField(null=True, verbose_name='Description')),
                ('description_ru', models.TextField(null=True, verbose_name='Description')),
                ('description_fi', models.TextField(null=True, verbose_name='Description')),
                ('price', models.DecimalField(decimal_places=2, max_digits=11, verbose_name='Price')),
                ('engine_volume', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Engine Volume')),
                ('mileage', models.PositiveIntegerField(verbose_name='Mileage')),
                ('warranty', models.BooleanField(verbose_name='Warranty')),
                ('slug', models.SlugField(unique=True, verbose_name='URL Path')),
                ('body', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.body', verbose_name='Body Type')),
            ],
            options={
                'verbose_name': 'Car',
                'verbose_name_plural': 'Cars',
            },
        ),
        migrations.CreateModel(
            name='Condition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Condition')),
                ('name_en', models.CharField(max_length=50, null=True, verbose_name='Condition')),
                ('name_ru', models.CharField(max_length=50, null=True, verbose_name='Condition')),
                ('name_fi', models.CharField(max_length=50, null=True, verbose_name='Condition')),
                ('slug', models.SlugField(null=True, unique=True, verbose_name='URL Postfix')),
            ],
        ),
        migrations.CreateModel(
            name='Engine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Engine')),
                ('name_en', models.CharField(max_length=50, null=True, verbose_name='Engine')),
                ('name_ru', models.CharField(max_length=50, null=True, verbose_name='Engine')),
                ('name_fi', models.CharField(max_length=50, null=True, verbose_name='Engine')),
                ('slug', models.SlugField(null=True, unique=True, verbose_name='URL Postfix')),
            ],
        ),
        migrations.CreateModel(
            name='Gearbox',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Gearbox')),
                ('name_en', models.CharField(max_length=50, null=True, verbose_name='Gearbox')),
                ('name_ru', models.CharField(max_length=50, null=True, verbose_name='Gearbox')),
                ('name_fi', models.CharField(max_length=50, null=True, verbose_name='Gearbox')),
                ('slug', models.SlugField(null=True, unique=True, verbose_name='URL Postfix')),
            ],
            options={
                'verbose_name': 'Gearbox',
                'verbose_name_plural': 'Gearboxes',
            },
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Date')),
                ('time', models.TimeField(verbose_name='Time')),
                ('name', models.CharField(max_length=50, null=True, verbose_name='Name')),
                ('is_submitted', models.BooleanField(verbose_name='Submitted?')),
                ('duration', models.IntegerField(verbose_name='Duration')),
                ('email', models.EmailField(max_length=100, verbose_name='Email')),
                ('phone_number', models.PositiveBigIntegerField(verbose_name='Phone Number')),
                ('visited', models.BooleanField(verbose_name='Visited?')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Creation Time')),
            ],
            options={
                'verbose_name': 'Schedule',
                'verbose_name_plural': 'Schedule',
            },
        ),
        migrations.CreateModel(
            name='ServiceType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Maintenance', max_length=150, verbose_name='Service Name')),
                ('title_en', models.CharField(default='Maintenance', max_length=150, null=True, verbose_name='Service Name')),
                ('title_ru', models.CharField(default='Maintenance', max_length=150, null=True, verbose_name='Service Name')),
                ('title_fi', models.CharField(default='Maintenance', max_length=150, null=True, verbose_name='Service Name')),
                ('prefix', models.CharField(blank=True, default='starts with', max_length=50, verbose_name='Price prefix')),
                ('prefix_en', models.CharField(blank=True, default='starts with', max_length=50, null=True, verbose_name='Price prefix')),
                ('prefix_ru', models.CharField(blank=True, default='starts with', max_length=50, null=True, verbose_name='Price prefix')),
                ('prefix_fi', models.CharField(blank=True, default='starts with', max_length=50, null=True, verbose_name='Price prefix')),
                ('postfix', models.CharField(blank=True, default='/h', max_length=50, verbose_name='Time Rate')),
                ('postfix_en', models.CharField(blank=True, default='/h', max_length=50, null=True, verbose_name='Time Rate')),
                ('postfix_ru', models.CharField(blank=True, default='/h', max_length=50, null=True, verbose_name='Time Rate')),
                ('postfix_fi', models.CharField(blank=True, default='/h', max_length=50, null=True, verbose_name='Time Rate')),
                ('slug', models.SlugField(unique=True, verbose_name='URL Postfix')),
            ],
            options={
                'verbose_name': 'Service Type',
                'verbose_name_plural': 'Service Types',
            },
        ),
        migrations.CreateModel(
            name='Wheel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Wheel')),
                ('name_en', models.CharField(max_length=50, null=True, verbose_name='Wheel')),
                ('name_ru', models.CharField(max_length=50, null=True, verbose_name='Wheel')),
                ('name_fi', models.CharField(max_length=50, null=True, verbose_name='Wheel')),
                ('slug', models.SlugField(null=True, unique=True, verbose_name='URL Postfix')),
            ],
        ),
        migrations.CreateModel(
            name='WheelDrive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Wheel Drive')),
                ('name_en', models.CharField(max_length=50, null=True, verbose_name='Wheel Drive')),
                ('name_ru', models.CharField(max_length=50, null=True, verbose_name='Wheel Drive')),
                ('name_fi', models.CharField(max_length=50, null=True, verbose_name='Wheel Drive')),
                ('slug', models.SlugField(null=True, unique=True, verbose_name='URL Postfix')),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Service Name')),
                ('title_en', models.CharField(max_length=150, null=True, verbose_name='Service Name')),
                ('title_ru', models.CharField(max_length=150, null=True, verbose_name='Service Name')),
                ('title_fi', models.CharField(max_length=150, null=True, verbose_name='Service Name')),
                ('description', models.TextField(verbose_name='Description')),
                ('description_en', models.TextField(null=True, verbose_name='Description')),
                ('description_ru', models.TextField(null=True, verbose_name='Description')),
                ('description_fi', models.TextField(null=True, verbose_name='Description')),
                ('duration', models.PositiveIntegerField(verbose_name='Duration')),
                ('photo', models.ImageField(null=True, upload_to='services/', verbose_name='Service Picture')),
                ('price', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Price')),
                ('slug', models.SlugField(unique=True, verbose_name='URL Postfix')),
                ('service_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.servicetype', verbose_name='Service Type')),
            ],
            options={
                'verbose_name': 'Service',
                'verbose_name_plural': 'Services',
            },
        ),
        migrations.CreateModel(
            name='CarPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('capture', models.CharField(max_length=511, null=True, verbose_name='Capture')),
                ('image', models.ImageField(upload_to='cars/', verbose_name='Image')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.car')),
            ],
            options={
                'verbose_name': 'Photo',
                'verbose_name_plural': 'Photos',
            },
        ),
        migrations.AddField(
            model_name='car',
            name='condition',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.condition', verbose_name='Condition'),
        ),
        migrations.AddField(
            model_name='car',
            name='engine_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.engine', verbose_name='Engine Type'),
        ),
        migrations.AddField(
            model_name='car',
            name='gearbox',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.gearbox', verbose_name='Gearbox'),
        ),
        migrations.AddField(
            model_name='car',
            name='wheel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.wheel', verbose_name='Wheel'),
        ),
        migrations.AddField(
            model_name='car',
            name='wheel_drive',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.wheeldrive', verbose_name='Wheel Drive'),
        ),
    ]
