# Generated by Django 3.2.9 on 2021-12-22 16:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Schedule',
        ),
        migrations.RenameField(
            model_name='body',
            old_name='name',
            new_name='title',
        ),
        migrations.RenameField(
            model_name='body',
            old_name='name_fi',
            new_name='title_en',
        ),
        migrations.RenameField(
            model_name='body',
            old_name='name_en',
            new_name='title_fi',
        ),
        migrations.RenameField(
            model_name='body',
            old_name='name_ru',
            new_name='title_ru',
        ),
        migrations.RenameField(
            model_name='condition',
            old_name='name',
            new_name='title',
        ),
        migrations.RenameField(
            model_name='condition',
            old_name='name_en',
            new_name='title_en',
        ),
        migrations.RenameField(
            model_name='condition',
            old_name='name_fi',
            new_name='title_fi',
        ),
        migrations.RenameField(
            model_name='condition',
            old_name='name_ru',
            new_name='title_ru',
        ),
        migrations.RenameField(
            model_name='engine',
            old_name='name',
            new_name='title',
        ),
        migrations.RenameField(
            model_name='engine',
            old_name='name_en',
            new_name='title_en',
        ),
        migrations.RenameField(
            model_name='engine',
            old_name='name_fi',
            new_name='title_fi',
        ),
        migrations.RenameField(
            model_name='engine',
            old_name='name_ru',
            new_name='title_ru',
        ),
        migrations.RenameField(
            model_name='gearbox',
            old_name='name',
            new_name='title',
        ),
        migrations.RenameField(
            model_name='gearbox',
            old_name='name_en',
            new_name='title_en',
        ),
        migrations.RenameField(
            model_name='gearbox',
            old_name='name_fi',
            new_name='title_fi',
        ),
        migrations.RenameField(
            model_name='gearbox',
            old_name='name_ru',
            new_name='title_ru',
        ),
        migrations.RenameField(
            model_name='wheel',
            old_name='name',
            new_name='title',
        ),
        migrations.RenameField(
            model_name='wheel',
            old_name='name_en',
            new_name='title_en',
        ),
        migrations.RenameField(
            model_name='wheel',
            old_name='name_fi',
            new_name='title_fi',
        ),
        migrations.RenameField(
            model_name='wheel',
            old_name='name_ru',
            new_name='title_ru',
        ),
        migrations.RenameField(
            model_name='wheeldrive',
            old_name='name',
            new_name='title',
        ),
        migrations.RenameField(
            model_name='wheeldrive',
            old_name='name_en',
            new_name='title_en',
        ),
        migrations.RenameField(
            model_name='wheeldrive',
            old_name='name_fi',
            new_name='title_fi',
        ),
        migrations.RenameField(
            model_name='wheeldrive',
            old_name='name_ru',
            new_name='title_ru',
        ),
        migrations.AddField(
            model_name='carphoto',
            name='capture_en',
            field=models.CharField(max_length=511, null=True, verbose_name='Capture'),
        ),
        migrations.AddField(
            model_name='carphoto',
            name='capture_fi',
            field=models.CharField(max_length=511, null=True, verbose_name='Capture'),
        ),
        migrations.AddField(
            model_name='carphoto',
            name='capture_ru',
            field=models.CharField(max_length=511, null=True, verbose_name='Capture'),
        ),
        migrations.AlterField(
            model_name='carphoto',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.car', verbose_name='Car'),
        ),
    ]
