# Generated by Django 3.2.9 on 2022-01-27 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20211222_1914'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='carphoto',
            options={'verbose_name': 'Car Picture', 'verbose_name_plural': 'Car Pictures'},
        ),
        migrations.AlterModelOptions(
            name='wheeldrive',
            options={'verbose_name': 'Wheel Drive', 'verbose_name_plural': 'Wheels Drive'},
        ),
        migrations.AlterField(
            model_name='body',
            name='slug',
            field=models.SlugField(help_text='unique url path', null=True, unique=True, verbose_name='URL Postfix'),
        ),
        migrations.AlterField(
            model_name='car',
            name='slug',
            field=models.SlugField(help_text='unique url path', unique=True, verbose_name='URL Path'),
        ),
        migrations.AlterField(
            model_name='condition',
            name='slug',
            field=models.SlugField(help_text='unique url path', null=True, unique=True, verbose_name='URL Postfix'),
        ),
        migrations.AlterField(
            model_name='engine',
            name='slug',
            field=models.SlugField(help_text='unique url path', null=True, unique=True, verbose_name='URL Postfix'),
        ),
        migrations.AlterField(
            model_name='gearbox',
            name='slug',
            field=models.SlugField(help_text='unique url path', null=True, unique=True, verbose_name='URL Postfix'),
        ),
        migrations.AlterField(
            model_name='service',
            name='slug',
            field=models.SlugField(help_text='unique url path', unique=True, verbose_name='URL Postfix'),
        ),
        migrations.AlterField(
            model_name='servicetype',
            name='slug',
            field=models.SlugField(help_text='unique url path', unique=True, verbose_name='URL Postfix'),
        ),
        migrations.AlterField(
            model_name='wheel',
            name='slug',
            field=models.SlugField(help_text='unique url path', null=True, unique=True, verbose_name='URL Postfix'),
        ),
        migrations.AlterField(
            model_name='wheeldrive',
            name='slug',
            field=models.SlugField(help_text='unique url path', null=True, unique=True, verbose_name='URL Postfix'),
        ),
    ]
