# Generated by Django 3.2.9 on 2022-01-27 20:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20220127_0938'),
    ]

    operations = [
        migrations.RenameField(
            model_name='service',
            old_name='price',
            new_name='default_price',
        ),
        migrations.AddField(
            model_name='service',
            name='price_depends',
            field=models.BooleanField(default=False, verbose_name='Price depends?'),
        ),
        migrations.AddField(
            model_name='service',
            name='related_service',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rel_one', to='main.service', verbose_name='Related Service'),
        ),
        migrations.AddField(
            model_name='service',
            name='related_service_two',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rel_two', to='main.service', verbose_name='Related Service 2'),
        ),
        migrations.CreateModel(
            name='Price',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price_from', models.PositiveIntegerField(verbose_name='Price From')),
                ('price_to', models.PositiveIntegerField(verbose_name='Price To')),
                ('price_prefix', models.CharField(max_length=10, null=True, verbose_name='Price Prefix')),
                ('price_postfix', models.CharField(max_length=10, null=True, verbose_name='Price Postfix')),
                ('body', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.body')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.service')),
            ],
            options={
                'verbose_name': 'Price',
                'verbose_name_plural': 'Prices',
            },
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_sum', models.PositiveIntegerField()),
                ('service', models.ManyToManyField(to='main.Service')),
            ],
        ),
    ]
