# Generated by Django 4.0.1 on 2022-01-29 19:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0001_initial'),
        ('main', '0005_remove_price_price_postfix_remove_price_price_prefix_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='body',
        ),
        migrations.RemoveField(
            model_name='car',
            name='condition',
        ),
        migrations.RemoveField(
            model_name='car',
            name='engine_type',
        ),
        migrations.RemoveField(
            model_name='car',
            name='gearbox',
        ),
        migrations.RemoveField(
            model_name='car',
            name='wheel',
        ),
        migrations.RemoveField(
            model_name='car',
            name='wheel_drive',
        ),
        migrations.RemoveField(
            model_name='carphoto',
            name='subject',
        ),
        migrations.AlterField(
            model_name='price',
            name='body',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cars.body'),
        ),
        migrations.DeleteModel(
            name='Body',
        ),
        migrations.DeleteModel(
            name='Car',
        ),
        migrations.DeleteModel(
            name='CarPhoto',
        ),
        migrations.DeleteModel(
            name='Condition',
        ),
        migrations.DeleteModel(
            name='Engine',
        ),
        migrations.DeleteModel(
            name='Gearbox',
        ),
        migrations.DeleteModel(
            name='Wheel',
        ),
        migrations.DeleteModel(
            name='WheelDrive',
        ),
    ]
