# Generated by Django 4.0.1 on 2022-01-29 19:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Body',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Body Type')),
                ('title_en', models.CharField(max_length=50, null=True, verbose_name='Body Type')),
                ('title_ru', models.CharField(max_length=50, null=True, verbose_name='Body Type')),
                ('title_fi', models.CharField(max_length=50, null=True, verbose_name='Body Type')),
                ('slug', models.SlugField(help_text='unique url path', null=True, unique=True, verbose_name='URL Postfix')),
            ],
            options={
                'verbose_name': 'Body Type',
                'verbose_name_plural': 'Body Types',
            },
        ),
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=100, verbose_name='Brand')),
                ('model', models.CharField(max_length=100, verbose_name='Model')),
                ('year', models.PositiveIntegerField(verbose_name='Year')),
                ('vin', models.CharField(max_length=50, verbose_name='VIN-number')),
                ('color', models.CharField(max_length=50, verbose_name='Color')),
                ('color_en', models.CharField(max_length=50, null=True, verbose_name='Color')),
                ('color_ru', models.CharField(max_length=50, null=True, verbose_name='Color')),
                ('color_fi', models.CharField(max_length=50, null=True, verbose_name='Color')),
                ('description', models.TextField(verbose_name='Description')),
                ('description_en', models.TextField(null=True, verbose_name='Description')),
                ('description_ru', models.TextField(null=True, verbose_name='Description')),
                ('description_fi', models.TextField(null=True, verbose_name='Description')),
                ('price', models.DecimalField(decimal_places=2, max_digits=11, verbose_name='Price')),
                ('engine_volume', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Engine Volume')),
                ('mileage', models.PositiveIntegerField(verbose_name='Mileage')),
                ('warranty', models.BooleanField(verbose_name='Warranty')),
                ('slug', models.SlugField(help_text='unique url path', unique=True, verbose_name='URL Path')),
                ('body', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cars.body', verbose_name='Body Type')),
            ],
            options={
                'verbose_name': 'Car',
                'verbose_name_plural': 'Cars',
            },
        ),
        migrations.CreateModel(
            name='Condition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Condition')),
                ('title_en', models.CharField(max_length=50, null=True, verbose_name='Condition')),
                ('title_ru', models.CharField(max_length=50, null=True, verbose_name='Condition')),
                ('title_fi', models.CharField(max_length=50, null=True, verbose_name='Condition')),
                ('slug', models.SlugField(help_text='unique url path', null=True, unique=True, verbose_name='URL Postfix')),
            ],
        ),
        migrations.CreateModel(
            name='Engine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Engine')),
                ('title_en', models.CharField(max_length=50, null=True, verbose_name='Engine')),
                ('title_ru', models.CharField(max_length=50, null=True, verbose_name='Engine')),
                ('title_fi', models.CharField(max_length=50, null=True, verbose_name='Engine')),
                ('slug', models.SlugField(help_text='unique url path', null=True, unique=True, verbose_name='URL Postfix')),
            ],
        ),
        migrations.CreateModel(
            name='Gearbox',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Gearbox')),
                ('title_en', models.CharField(max_length=50, null=True, verbose_name='Gearbox')),
                ('title_ru', models.CharField(max_length=50, null=True, verbose_name='Gearbox')),
                ('title_fi', models.CharField(max_length=50, null=True, verbose_name='Gearbox')),
                ('slug', models.SlugField(help_text='unique url path', null=True, unique=True, verbose_name='URL Postfix')),
            ],
            options={
                'verbose_name': 'Gearbox',
                'verbose_name_plural': 'Gearboxes',
            },
        ),
        migrations.CreateModel(
            name='Wheel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Wheel')),
                ('title_en', models.CharField(max_length=50, null=True, verbose_name='Wheel')),
                ('title_ru', models.CharField(max_length=50, null=True, verbose_name='Wheel')),
                ('title_fi', models.CharField(max_length=50, null=True, verbose_name='Wheel')),
                ('slug', models.SlugField(help_text='unique url path', null=True, unique=True, verbose_name='URL Postfix')),
            ],
        ),
        migrations.CreateModel(
            name='WheelDrive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Wheel Drive')),
                ('title_en', models.CharField(max_length=50, null=True, verbose_name='Wheel Drive')),
                ('title_ru', models.CharField(max_length=50, null=True, verbose_name='Wheel Drive')),
                ('title_fi', models.CharField(max_length=50, null=True, verbose_name='Wheel Drive')),
                ('slug', models.SlugField(help_text='unique url path', null=True, unique=True, verbose_name='URL Postfix')),
            ],
            options={
                'verbose_name': 'Wheel Drive',
                'verbose_name_plural': 'Wheels Drive',
            },
        ),
        migrations.CreateModel(
            name='CarPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('capture', models.CharField(max_length=511, null=True, verbose_name='Capture')),
                ('capture_en', models.CharField(max_length=511, null=True, verbose_name='Capture')),
                ('capture_ru', models.CharField(max_length=511, null=True, verbose_name='Capture')),
                ('capture_fi', models.CharField(max_length=511, null=True, verbose_name='Capture')),
                ('image', models.ImageField(upload_to='cars/', verbose_name='Image')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cars.car', verbose_name='Car')),
            ],
            options={
                'verbose_name': 'Car Picture',
                'verbose_name_plural': 'Car Pictures',
            },
        ),
        migrations.AddField(
            model_name='car',
            name='condition',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cars.condition', verbose_name='Condition'),
        ),
        migrations.AddField(
            model_name='car',
            name='engine_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cars.engine', verbose_name='Engine Type'),
        ),
        migrations.AddField(
            model_name='car',
            name='gearbox',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cars.gearbox', verbose_name='Gearbox'),
        ),
        migrations.AddField(
            model_name='car',
            name='wheel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cars.wheel', verbose_name='Wheel'),
        ),
        migrations.AddField(
            model_name='car',
            name='wheel_drive',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cars.wheeldrive', verbose_name='Wheel Drive'),
        ),
    ]
